# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 03666af8768d6d2085904c3642f874a1992209aa3e02a1e9596034c03b034aafe20e8ca4c56e83c2880b735b03d9f9509d8ea5c19815aa70f3b3fd208e021a41

test:
  secret_key_base: 9b6209eb58aaf8e5c2ed874739ae8f90c33017b004d339946d46dbb7791acafdfc79ff6218ac1f94bf72480bcfbd256a769705bdb737585347c0c46a683ec79c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
